// <auto-generated />
namespace Ecommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCart3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCart3));
        
        string IMigrationMetadata.Id
        {
            get { return "201608291231359_AddCart3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
